openapi: 3.0.0
info:
  title: Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/test/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-test
      description: Test test test
      requestBody: {}
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas: {}
